[features]
seeds = false
skip-lint = false
[programs.localnet]
bonk_paper_scissors = "32TtZ4MYWk6zzwg8Eok3x6m85JQgcVsN97cGfUhfpNb9"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/kevinrodriguez/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
